name: 1.9.3
published: true
documentations:
    - installation
    - configuration
    - operationalguide
    - datasheet
    - integrations
    - faq
    - release-notes
    - troubleshooting
references:
    - asdf
    - metadefender-sandbox-api-reference-v1
