title: 'OPSWAT Filescan API Reference v1'
description: null
published: true
downloadable: true
expandable: false
showContentType: false
showAccept: false
showTryItOut: false
indexCollapsible: false
showOAuth2: false
showRequestPayloadOnly: false
dontCapitalizeTags: false
