title: Backend
published: true
description: 'The data can include metrics, error logs, and other types of data that can provide insights into backend structure.'
collapsed: true
collapsedCategories: false
showLastUpdated: false
showLastUpdateUser: false
locale: en_us
