title: 'Operational Guide'
published: true
description: 'Detailed documentation guide regarding the operations of MetaDefender Sandbox'
collapsed: true
collapsedCategories: false
showLastUpdated: false
showLastUpdateUser: false
locale: en_us
