title: 'API Reference'
description: 'API documentation for MetaDefender Sandbox.'
published: false
downloadable: true
expandable: false
showContentType: false
showAccept: false
showTryItOut: false
indexCollapsible: false
showOAuth2: false
showRequestPayloadOnly: false
dontCapitalizeTags: false
