title: fsTransform
published: true
description: 'What is the fsTransform API, and how does it work?'
collapsed: true
collapsedCategories: false
showLastUpdated: false
showLastUpdateUser: false
locale: en_us
