title: Overview
published: true
description: 'Provides a high-level overview of the product MetaDefender Sandbox, containing key files and documents related to its development and operation.'
collapsed: true
collapsedCategories: false
showLastUpdated: false
showLastUpdateUser: false
locale: en_us
