title: 'System Guide'
published: true
description: 'Architecture, folder structures, retention policies...'
collapsed: true
collapsedCategories: false
showLastUpdated: false
showLastUpdateUser: false
locale: en_us
