name: 1.7.4
published: true
documentations:
    - installation
    - configuration
    - operationalguide
    - datasheet
    - integrations
    - backend
    - faq
    - release-notes
    - troubleshooting
references:
    - opswat-filescan
    - metadefender-cloud-threat-intelligence-api-v5
