name: 1.8.1
published: true
documentations:
    - installation
    - configuration
    - operationalguide
    - datasheet
    - integrations
    - backend
    - faq
    - release-notes
    - troubleshooting
references:
    - opswat-filescan
    - asdf
