name: 2.2.0
published: true
documentations:
    - datasheet
    - installation
    - adminguide
    - configuration
    - integrations
    - release-notes
    - troubleshooting
    - faq
references:
    - asdf
    - metadefender-sandbox-api-reference
