name: v1.70
published: true
documentations:
    - datasheet
    - faq
    - system-guide
    - installation-guide
    - troubleshooting-guide
    - aws-quick-launch
    - fsbroker
    - fstransform
references:
    - opswat-filescan
