name: 3.2.0
published: true
documentations:
    - datasheet
    - integrations
    - installation
    - configuration
    - adminguide
    - release-notes
    - faq
    - troubleshooting
    - '-test-'
references:
    - metadefender-sandbox-api-reference
