name: 1.9.2
published: true
documentations:
    - installation
    - configuration
    - operationalguide
    - datasheet
    - integrations
    - backend
    - faq
    - release-notes
    - troubleshooting
    - test
references:
    - opswat-filescan
    - asdf
    - metadefender-sandbox-api-reference-v1
